services:
    app:
        build:
            context: ./
            dockerfile: app.dockerfile
        working_dir: /var/www
        environment:
            - XDEBUG_MODE=coverage
        volumes:
            - ./:/var/www
        depends_on:
            - "database"
    web:
        build:
            context: ./
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 80:80
        depends_on:
            - "app" 
    database:
        image: mysql:8.4.9
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - 33061:3306

volumes:
    dbdata:
